server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kvp_bot
    username: vladbright
    password: vladbright
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
